# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuCVR35nuLkwMyVI6OpFt3rqB5EyL4ZJ
"""

import pandas as pd

data = pd.read_csv('/organizations-100.csv')
type(data)

data.info()

data.describe()

data=data.drop_duplicates()
data

data.isnull()

data.isnull().sum()

data.notnull()

data.notnull().sum()

data2=data.fillna(value=0)
data2

data2.isnull().sum().sum()

data3=data.fillna(method='pad')#forward filling
data3

data4=data.fillna(method='bfill')
data4

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

data4.drop(['Organization Id'],axis=1,inplace=True)
data4.columns
data4

new_Data = data.select_dtypes(include=[np.number])

Q1= new_Data.quantile(0.25)
Q3= new_Data.quantile(0.75)
IQR=Q3-Q1
print(IQR)

new_Data.columns

numeric_data=new_Data[~((new_Data<(Q1-1.5*IQR)) |(new_Data>(Q3+1.5*IQR))).any(axis=1)]
numeric_data